name: Release Artifacts

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency: ${{ github.workflow }}-${{ github.event.release.tag_name }}

jobs:
  upload:
    name: Upload Extension
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm turbo run build

      - name: Create Zip
        working-directory: apps/extension
        run: pnpm zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: apps/extension/.output/*.zip
